import './globals.css'
import type { Metadata } from 'next'
import { Heebo } from 'next/font/google'

// dam.org.il site mainly uses Heebo font.
// mdais.org site mainly uses Assistant font.
// (Both are under Open Font License)
const heebo = Heebo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={heebo.className}>{children}</body>
    </html>
  )
}
